/* ===== Tap to Enterprise — bilingual content (EN / ES) ===== */
window.CONTENT = {
  en: {
    nav: { method:"Method", services:"Services", clients:"Clients", about:"About", contact:"Contact", cta:"Free diagnostic" },
    langLabel:"ES",

    hero:{
      eyebrow:"The FORMA Method",
      title_a:"Build once.",
      title_b:"Grow forever.",
      lede:"We help small business owners formalize, organize and automate their company with the FORMA Method — the proven roadmap that takes you from surviving to growing.",
      cta1:"Take the free diagnostic",
      cta2:"See how FORMA works",
      stat1:["20+ yrs","Enterprise transformation experience"],
      stat2:["5 phases","One clear roadmap"],
      stat3:["MX · USA","Serving both markets"],
    },

    forma:{
      eyebrow:"How we do it",
      title:"Five phases. One system.",
      lede:"FORMA is the same operating system that powers the world's largest corporations — rebuilt for the person who wakes up at 5am to run their business.",
      tagline:"The proven roadmap for businesses ready to stop surviving and start growing.",
      phases:[
        { k:"F", name:"Formalization", short:"Get legal. Get protected. Get access.",
          body:"Get your business legally established and fiscally active — legal structure, tax registration, banking and permits. The foundation everything else stands on." },
        { k:"O", name:"Organization", short:"Build processes. Define roles. Measure what matters.",
          body:"Turn the chaos in your head into clear processes. Define who does what, and put numbers on the things that actually move your business." },
        { k:"R", name:"Resources", short:"Fund your growth.",
          body:"Access funding and government programs you didn't know existed — capital, grants and support built for businesses exactly like yours." },
        { k:"M", name:"Brand", short:"Build your identity and digital presence.",
          body:"Build a brand and digital presence that looks as professional as you are — powered by AI tools that do the heavy lifting." },
        { k:"A", name:"Automation", short:"Let technology work for you — 24/7.",
          body:"Put technology to work so your business runs without you — selling, following up and operating around the clock, even while you sleep." },
      ],
      pick:"Click a phase to explore it",
    },

    services:{
      eyebrow:"Services",
      title:"Start free. Go as far as you want.",
      lede:"Every service is a door into FORMA — begin with a free diagnostic, then build at your own pace.",
      coreLabel:"Core paths",
      core:[
        { tag:"Free", name:"FORMA Diagnostic", sub:"Your starting point — no cost, no commitment",
          body:"A quick assessment that tells you exactly where your business stands and what your next step should be. You leave with a personalized roadmap. Free, always.", featured:true },
        { tag:"Flexible", name:"Phase Implementation", sub:"One phase at a time, at your pace",
          body:"Hands-on guidance through each phase of FORMA. You choose where to start based on your diagnostic results." },
        { tag:"10 weeks", name:"FORMA Program", sub:"The full transformation, start to finish",
          body:"A structured group program through all five phases — practical, actionable and built for real businesses. In person, online or hybrid." },
        { tag:"Ongoing", name:"Monthly Advisory", sub:"A thinking partner as you grow",
          body:"Ongoing support, accountability and strategic guidance for businesses already moving and ready to go further." },
      ],
      alaLabel:"À la carte",
      alaSub:"Only need one piece? Each one is a door into FORMA.",
      ala:[
        { name:"Business Formalization", body:"Step-by-step guidance to formalize — legal structure, tax, banking and permits. Mexico & USA." },
        { name:"Web Design", body:"Professional, mobile-friendly websites built for small businesses. Fast, clean and built to convert." },
        { name:"E-Commerce", body:"We set up your online store so your products reach customers anywhere — without you there to sell." },
        { name:"Point of Sale Integration", body:"Connect physical and digital sales — inventory, payments and reporting in one place." },
        { name:"AI Business Documents", body:"A growing library of ready-to-use documents — contracts, templates, plans and trackers. Buy once, use forever." },
        { name:"Courses", body:"Practical, no-fluff courses on formalization, digital presence and automation. For people who learn by doing." },
        { name:"Social Media Design", body:"Profile setup, branded templates and your first posts ready to publish. Consistent and professional." },
      ],
      pricing:"Pricing tailored to each business — always start with your free diagnostic.",
      cta:"Start with your free diagnostic",
    },

    clients:{
      eyebrow:"Clients & references",
      title:"Be among the first.",
      quote:"Be among the first businesses to go through the FORMA Method. Early clients receive personalized attention directly from the founder.",
      sub:"This isn't a waitlist — it's a front-row seat. The first businesses through FORMA work shoulder-to-shoulder with Isabel herself.",
      perks:[
        ["Direct founder access","Work one-on-one with Isabel, not a junior team."],
        ["Founding-client pricing","Early-access terms that won't return later."],
        ["Shape the method","Your feedback builds the program everyone gets next."],
      ],
      cta:"Claim your founding spot",
    },

    about:{
      eyebrow:"Who we are",
      title:"Enterprise systems, without the enterprise price tag.",
      name:"Isabel Castro",
      role:"Founder · IT Executive",
      p1:"Isabel Castro is an IT executive with 20+ years leading digital transformations at global companies including British American Tobacco, ATOS and FLS.",
      p2:"She built the FORMA Method to give small business owners access to the same systems that power the world's largest corporations — without the corporate price tag.",
      p3:"She believes the person who wakes up at 5am to run their business deserves a system as powerful as any Fortune 500 company. That belief is FORMA.",
      pull:"That belief is FORMA.",
      logos:["British American Tobacco","ATOS","FLS"],
      logosLabel:"Two decades inside",
    },

    contact:{
      eyebrow:"Contact",
      title:"Your next step is free.",
      lede:"Take the FORMA diagnostic and walk away with a clear roadmap — no cost, no commitment.",
      cta:"Take the free diagnostic",
      emailLabel:"Email",
      email:"isabel@taptoenterprise.com",
      emailNote:"Setting up — reach out via the form for now.",
      siteLabel:"Web",
      site:"taptoenterprise.com",
      locLabel:"Based in",
      loc:"Monterrey, México",
      locNote:"Serving México & the USA",
      formName:"Your name",
      formEmail:"Email",
      formBiz:"What's your business?",
      formMsg:"Where do you feel stuck? (optional)",
      formSend:"Request my free diagnostic",
      formNote:"We'll reply within one business day.",
    },

    footer:{
      tagline:"Build once. Grow forever.",
      rights:"All rights reserved.",
      method:"The FORMA Method",
      back:"Back to top",
    },
  },

  es: {
    nav: { method:"Método", services:"Servicios", clients:"Clientes", about:"Nosotros", contact:"Contacto", cta:"Diagnóstico gratis" },
    langLabel:"EN",

    hero:{
      eyebrow:"El Método FORMA",
      title_a:"Constrúyelo una vez.",
      title_b:"Crece para siempre.",
      lede:"Ayudamos a dueños de pequeños negocios a formalizar, organizar y automatizar su empresa con el Método FORMA — la ruta probada que te lleva de sobrevivir a crecer.",
      cta1:"Haz el diagnóstico gratis",
      cta2:"Ve cómo funciona FORMA",
      stat1:["20+ años","Experiencia en transformación empresarial"],
      stat2:["5 fases","Una ruta clara"],
      stat3:["MX · USA","Atendemos ambos mercados"],
    },

    forma:{
      eyebrow:"Cómo lo hacemos",
      title:"Cinco fases. Un sistema.",
      lede:"FORMA es el mismo sistema operativo que mueve a las corporaciones más grandes del mundo — reconstruido para quien se levanta a las 5am a sacar adelante su negocio.",
      tagline:"La ruta probada para negocios listos para dejar de sobrevivir y empezar a crecer.",
      phases:[
        { k:"F", name:"Formalización", short:"Legal, protegido y con acceso.",
          body:"Establece tu negocio legal y fiscalmente — estructura legal, alta de impuestos, banca y permisos. La base sobre la que se construye todo lo demás." },
        { k:"O", name:"Organización", short:"Crea procesos. Define roles. Mide lo que importa.",
          body:"Convierte el caos de tu cabeza en procesos claros. Define quién hace qué y pon números a lo que de verdad mueve tu negocio." },
        { k:"R", name:"Recursos", short:"Financia tu crecimiento.",
          body:"Accede a financiamiento y programas de gobierno que no sabías que existían — capital, apoyos y fondos hechos para negocios como el tuyo." },
        { k:"M", name:"Marca", short:"Construye tu identidad y presencia digital.",
          body:"Construye una marca y presencia digital tan profesional como tú — impulsada por herramientas de IA que hacen el trabajo pesado." },
        { k:"A", name:"Automatización", short:"Que la tecnología trabaje por ti — 24/7.",
          body:"Pon la tecnología a trabajar para que tu negocio opere sin ti — vendiendo, dando seguimiento y operando todo el día, incluso mientras duermes." },
      ],
      pick:"Haz clic en una fase para explorarla",
    },

    services:{
      eyebrow:"Servicios",
      title:"Empieza gratis. Llega tan lejos como quieras.",
      lede:"Cada servicio es una puerta hacia FORMA — empieza con un diagnóstico gratis y avanza a tu ritmo.",
      coreLabel:"Rutas principales",
      core:[
        { tag:"Gratis", name:"Diagnóstico FORMA", sub:"Tu punto de partida — sin costo, sin compromiso",
          body:"Una evaluación rápida que te dice exactamente dónde está tu negocio y cuál es tu siguiente paso. Te llevas una ruta personalizada. Gratis, siempre.", featured:true },
        { tag:"Flexible", name:"Implementación por Fase", sub:"Una fase a la vez, a tu ritmo",
          body:"Acompañamiento práctico en cada fase de FORMA. Tú eliges por dónde empezar según tu diagnóstico." },
        { tag:"10 semanas", name:"Programa FORMA", sub:"La transformación completa, de principio a fin",
          body:"Un programa grupal estructurado por las cinco fases — práctico, accionable y hecho para negocios reales. Presencial, en línea o híbrido." },
        { tag:"Continuo", name:"Asesoría Mensual", sub:"Un socio estratégico mientras creces",
          body:"Apoyo continuo, rendición de cuentas y guía estratégica para negocios que ya avanzan y quieren ir más lejos." },
      ],
      alaLabel:"A la carta",
      alaSub:"¿Solo necesitas una pieza? Cada una es una puerta hacia FORMA.",
      ala:[
        { name:"Formalización de Negocios", body:"Acompañamiento paso a paso para formalizar — estructura legal, impuestos, banca y permisos. México y USA." },
        { name:"Diseño Web", body:"Sitios profesionales y móviles para pequeños negocios. Rápidos, limpios y hechos para convertir." },
        { name:"E-Commerce", body:"Montamos tu tienda en línea para que tus productos lleguen a cualquier parte — sin que tengas que estar para vender." },
        { name:"Integración de Punto de Venta", body:"Conecta ventas físicas y digitales — inventario, pagos y reportes en un solo lugar." },
        { name:"Documentos con IA", body:"Una biblioteca creciente de documentos listos para usar — contratos, plantillas, planes y formatos. Cómpralo una vez, úsalo siempre." },
        { name:"Cursos", body:"Cursos prácticos y sin relleno sobre formalización, presencia digital y automatización. Para quien aprende haciendo." },
        { name:"Diseño de Redes Sociales", body:"Configuración de perfiles, plantillas de marca y tus primeras publicaciones listas. Consistente y profesional." },
      ],
      pricing:"Precios a la medida de cada negocio — siempre empieza con tu diagnóstico gratis.",
      cta:"Empieza con tu diagnóstico gratis",
    },

    clients:{
      eyebrow:"Clientes y referencias",
      title:"Sé de los primeros.",
      quote:"Sé de los primeros negocios en pasar por el Método FORMA. Los clientes fundadores reciben atención personalizada directamente de la fundadora.",
      sub:"Esto no es una lista de espera — es un asiento en primera fila. Los primeros negocios en FORMA trabajan hombro con hombro con Isabel.",
      perks:[
        ["Acceso directo a la fundadora","Trabaja uno a uno con Isabel, no con un equipo junior."],
        ["Precio de cliente fundador","Condiciones de acceso anticipado que no volverán después."],
        ["Da forma al método","Tu retroalimentación construye el programa que recibirán los demás."],
      ],
      cta:"Aparta tu lugar de fundador",
    },

    about:{
      eyebrow:"Quiénes somos",
      title:"Sistemas de gran empresa, sin el precio de gran empresa.",
      name:"Isabel Castro",
      role:"Fundadora · Ejecutiva de TI",
      p1:"Isabel Castro es una ejecutiva de TI con más de 20 años liderando transformaciones digitales en empresas globales como British American Tobacco, ATOS y FLS.",
      p2:"Creó el Método FORMA para dar a los dueños de pequeños negocios acceso a los mismos sistemas que mueven a las corporaciones más grandes del mundo — sin el precio corporativo.",
      p3:"Cree que quien se levanta a las 5am a sacar adelante su negocio merece un sistema tan poderoso como el de cualquier empresa Fortune 500. Esa convicción es FORMA.",
      pull:"Esa convicción es FORMA.",
      logos:["British American Tobacco","ATOS","FLS"],
      logosLabel:"Dos décadas dentro de",
    },

    contact:{
      eyebrow:"Contacto",
      title:"Tu siguiente paso es gratis.",
      lede:"Haz el diagnóstico FORMA y llévate una ruta clara — sin costo, sin compromiso.",
      cta:"Haz el diagnóstico gratis",
      emailLabel:"Correo",
      email:"isabel@taptoenterprise.com",
      emailNote:"En configuración — escríbenos por el formulario por ahora.",
      siteLabel:"Web",
      site:"taptoenterprise.com",
      locLabel:"Ubicados en",
      loc:"Monterrey, México",
      locNote:"Atendemos México y USA",
      formName:"Tu nombre",
      formEmail:"Correo",
      formBiz:"¿Cuál es tu negocio?",
      formMsg:"¿Dónde te sientes atorado? (opcional)",
      formSend:"Solicitar mi diagnóstico gratis",
      formNote:"Te respondemos en un día hábil.",
    },

    footer:{
      tagline:"Constrúyelo una vez. Crece para siempre.",
      rights:"Todos los derechos reservados.",
      method:"El Método FORMA",
      back:"Volver arriba",
    },
  },
};
